export const contactTypes = {
    SET_NAME_STATE: 'SET_NAME_STATE',
    SET_EMAIL_STATE: 'SET_EMAIL_STATE',
    SET_SUBJECT_STATE: 'SET_SUBJECT_STATE',
    SET_BODY_STATE: 'SET_BODY_STATE',
    SET_CONTACT_STATE_NULL: 'SET_CONTACT_STATE_NULL',
    TOGGLE_CONTACT_FORM: "TOGGLE_CONTACT_FORM"
}
